export enum UserStatus {
    REGISTERED = 'REGISTERED',
    REGISTERED_BY_ORDER = 'REGISTERED_BY_ORDER',
    OAUTHREGISTERED = 'OAUTHREGISTERED',
    REGISTERED_AND_CONFIRMED = 'REGISTERED_AND_CONFIRMED',
    DISABLED = 'DISABLED'
}